### PR TITLE
Discussion about clang format

### PR DESCRIPTION
**Pull request by HenningScheufler**
how to apply change to the whole project
```
find . -name '*.cpp' -o -name '*.hpp' | xargs clang-format -i
```

### CODE REVIEW

**Comment by HenningScheufler** [comment]
@greole

**Comment by greole** [comment]
I would rather say we use the same pre-commit based approach as in NeoFOAM. To run clang-format and all other checks regardless of a git commit would be just a `pre-commit run --all`

**Comment by greole** [comment]
> how to apply change to the whole project
> 
> ```
> find . -name '*.cpp' -o -name '*.hpp' | xargs clang-format -i
> ```

I would rather say we use the same pre-commit based approach as in NeoFOAM. To run clang-format and all other checks regardless of a git commit would be just a pre-commit run --all

**Review by greole — APPROVED** [review]
LGTM! But the corresponding check is failing.

**Pull request merged**
